### PR TITLE
Equipment post is modified to use the database.

### PR DESCRIPTION
**Pull request by Voursstrreds**
Equipment post may need more changes according to the given location input. It may change.

I modified the function to add data to the database, not the ordinary lists.

### CODE REVIEW

**Review by ahmetnecipg — CHANGES_REQUESTED** [review]
Necessary database tables and functions need to be imported from .dbinit file. In this case Equipmentpost table needs to be imported.

**Comment by Voursstrreds** [comment]
> Necessary database tables and functions need to be imported from .dbinit file. In this case Equipmentpost table needs to be imported.

I fixed this.

**Comment by Voursstrreds** [comment]
Now this function works.

**Review by supiket — APPROVED** [review]
The imports and request.json null checks are on-point. The returned value is jsonified correctly.

**Review by ibrahimbayat — APPROVED** [review]
Function is very clear and understandable. It controls all the possible missing parameters and posting accordingly. Finally it returns appropriate json format. I think this function can satisfy the needed functionality.

**Comment by Voursstrreds** [comment]
> Necessary database tables and functions need to be imported from .dbinit file. In this case Equipmentpost table needs to be imported.

Can you review this now again?

**Comment by Voursstrreds** [comment]
The session statements were forgotten, they were added.

**Review by supiket — COMMENTED** [review]
The function communicates with the database correctly and functions as intended. 

My only (optional) suggestion is renaming the variable `d1` to something like `creation_date` in
`d1 = datetime.today()`
for better readability.

**Review by supiket — COMMENTED** [review]
As we discussed with @Voursstrreds on Discord:
`Session = sessionmaker(db)`
`session = Session()`
Instead of starting a new session on equipment.py with the instructions above, `session` can be imported from `.dbinit`. 
This is optional since our focus is on functionality and this code works as is.

**Review by ahmetnecipg — APPROVED** [review]
Necessary imports were made. Approved

**Review by supiket — CHANGES_REQUESTED** [review]
I think `ownerId` should be changed to `ownerID`.
Also the non-nullable attributes in the `.dbinit` file are:
- In Post(base):
  - ownerID
  - title
  - creationDate
- In Equipmentpost(Post):
  - equipmentType
  - websiteName
  - link
 
Please make sure these are all checked for bad request (code 400).

**Comment by Voursstrreds** [comment]
> I think `ownerId` should be changed to `ownerID`.

ownerID is changed to the form that you say. For the other one, only the creationDate is not defined exactly, and it does not need this. The function itself calculates the time every time we invoke the function.

**Comment by supiket** [comment]
You are correct, for a second I though `creationDate` should also be checked but of course it is initialized from `datetime.today()`. My mistake.

**Review by supiket — APPROVED** [review]
Approved as are no further suggestions or corrections to be made.

**Pull request merged**
