### PR TITLE
Equipmentpost class is added.

### PR DESCRIPTION
**Pull request by Voursstrreds**
Equipmentpost class is added to the database.

### CODE REVIEW

**Review by ibrahimbayat — APPROVED** [review]
I think Equipmentpost class has correct column types and these is enough for our project's functionality.  And other changes in other classes seems correct to me.

**Comment by supiket** [comment]
Bugfixes, primary keys and newly added EquipmentPost class have been reviewed and approved.

**Review by supiket — APPROVED** [review]
Bugfixes, primary keys and newly added equipment post class looks correct, database-tables seems ready for merging.

Optional: May we change the class name from Equipmentpost to EquipmentPost?

**Comment by ege-kaya** [comment]
Is it really a good idea to put character limits on fields like equipment type, link etc? I feel like we may not really be able to guarantee that each entry will fit into those limits.

**Comment by berkaydoner** [comment]
I think, for the Comment and Answer tables, date columns should have the type DateTime, not Date. Because users will probably also want to see the time of the comments/answers.

Also, commentId column of Answer table is given as a foreign key to eventpost.PostID, it should be Comment.commentId, as the name suggests. I think that was a typo, it should be fixed.

**Comment by CenekSanzak** [comment]
In this pull request, Comment and Answer table is also added. Foreign key in the Answer table is fixed in the latest commit and Date type is changed to DateTime in both Answer and Comment tables.

**Pull request merged**
