### PR TITLE
get_user function is added.

### PR DESCRIPTION
**Pull request by Voursstrreds**
New function get_user is added. It searches the users through the database and returns the user according to the its nickname.

### CODE REVIEW

**Comment by Voursstrreds** [comment]
Libraries used in the get_user function is added to the code.

**Review by Voursstrreds — COMMENTED** [review]
Second overrided function is added. One finds the all users and the other one finds the users according to their nicknames. It still needs to be reviewed, it may contain errors that I could not see.

**Review by berkaydoner — CHANGES_REQUESTED** [review]
As I understand, two get_user() methods do different things. One returns all the user objects while the other one returns the user with the given user name. Method names should be different since they have different functionalities. I think overriding decreases the readability for this case.
Also, you didn't need to change app.py, but since we do not use it anymore, I don't see any problems with changing it.

**Comment by Voursstrreds** [comment]
> As I understand, two get_user() methods do different things. One returns all the user objects while the other one returns the user with the given user name. Method names should be different since they have different functionalities. I think overriding decreases the readability for this case.
> Also, you didn't need to change app.py, but since we do not use it anymore, I don't see any problems with changing it.

app.py is changed to make the file more readable, at least to prevent misuses :) Overrided function name is changed, it won't be overrided anymore. You can check this file again.

**Comment by Voursstrreds** [comment]
An API is used to find the user's location according to the existing input in the database. If the location name is a city, then the function returns all the user data + its country. If not exists or does not match, then it returns "not known". The returned dictionary includes one more argument. Be aware.
The function is not an overrided function anymore. The function names are changed.
nickname parameter of the function is changed to take user_id.

**Comment by Voursstrreds** [comment]
Again the bugs are removed. Also the API is deactivated due to the consistency.

**Review by ibrahimbayat — APPROVED** [review]
I think function is good now after the fixed bugs. I didn't see any errors or mistakes. It is more better without overriding now. It is more readable to me. I think other people can understand the functionality of this function better.

**Pull request merged**
