### PR TITLE
Event search

### PR DESCRIPTION
**Pull request by berkaydoner**
I modified the getNearbyEvents() functionality so that it uses the database queries.  I added some new filters such as age range, keyword search and date&time filters. I also added sorting mechanism for the results

I think these changes are enough for the event search functionality.

### CODE REVIEW

**Review by CenekSanzak — APPROVED** [review]
Search function has filters for all fields. It uses the db for queries. This task is complete.

**Review by ahmetnecipg — APPROVED** [review]
There is no apparent flaw. Does what it needs to be doing.

**Comment by berkaydoner** [comment]
I have changed the datetime format to DD/MM/YYYY HH:MM:SS, as it is more readable. Also, I added comments to my code to make it more readable. Since I tested my code using Postman and it  was also reviewed, I think we can merge it into the development branch.

**Comment by berkaydoner** [comment]
There were some conflicts that caused the merge to fail. I fixed them and now this pull request can be merged.

**Comment by berkaydoner** [comment]
There were some issues regarding the conflicts. However, conflicts are resolved now and the pull request has been merged to the development branch.

**Pull request merged**
