### PR TITLE
Notification table added

### PR DESCRIPTION
**Pull request by ahmetnecipg**
I added the notification database table by taking my teammates work reference

### CODE REVIEW

**Review by berkaydoner — CHANGES_REQUESTED** [review]
As I said in the previous pull request, type of recipientId should be BigInteger rather than Integer, as in users table. Also, since this recipientId corresponds to the user_id column of users table, it should be declared as a foreign key.

**Comment by ahmetnecipg** [comment]
> As I said in the previous pull request, type of recipientId should be BigInteger rather than Integer, as in users table. Also, since this recipientId corresponds to the user_id column of users table, it should be declared as a foreign key.

Changed the types of ID and recipientId to BigInteger. Also declared recipientId as a foreing key

**Review by berkaydoner — APPROVED** [review]
I think changes are enough to provide a notification functionality, all the necessary columns are given with correct types.

**Review by berkaydoner — CHANGES_REQUESTED** [review]
I think both blockingID and blockedID columns should be given as foreign keys to the user_id column of users table.

**Pull request merged**
