### PR TITLE
Adjusted GET equipments

### PR DESCRIPTION
**Pull request by ahmetnecipg**
Adjusted the GET equipment function. Now it retrieves an equipment from the database table "Equipmentpost" instead of a list.

### CODE REVIEW

**Review by berkaydoner — APPROVED** [review]
I do not see any problems with the function itself, it seems to be working. Maybe you can add some comments to your code to make it more readable. A few comments would be more than enough, and even if you do not add comments, function is mostly very clear. So, it is up to you, I approve the changes.

**Review by Voursstrreds — APPROVED** [review]
It seems it nicely works. Databases were added and the function uses the database properly. I approve this.

**Comment by berkaydoner** [comment]
I checked your last commit, I think you shouldn't return the status code 200 in your helper function. It should only be returned at the API function, otherwise the functionality probably would not work, since the return value of the helper function will be a tuple, which is not what you want.

**Comment by ahmetnecipg** [comment]
> I checked your last commit, I think you shouldn't return the status code 200 in your helper function. It should only be returned at the API function, otherwise the functionality probably would not work, since the return value of the helper function will be a tuple, which is not what you want.

Fixed.

**Comment by ahmetnecipg** [comment]
Reviewers approved and it seems to be working. I'm merging and closing this pull request.

**Pull request merged**
